### ISSUE TITLE
Lost custom header

### ISSUE THREAD

**Issue by 1280103995** [blake-simpson/expo-jwt#41]
Look the code: https://github.com/blake-simpson/expo-jwt/blob/master/lib/encoder.ts
```
//...

const defaultOptions = {
  algorithm: SupportedAlgorithms.HS256,
};

let _key: EncodingKey;

class Encoder {
  body: JWTBody;
  options: EncodingOptions;

  constructor(body: JWTBody, key: EncodingKey, options: EncodingOptions = {}) {
    this.body = body;
    this.options = { ...defaultOptions, ...options };

    _key = key;
  }

  buildHeader(): JWTHeader {
    return {
      alg: this.options.algorithm,
      typ: 'JWT',
    };
  }

  encodeAndSign(): JWTToken {
    const jsonHeader = JSON.stringify(this.buildHeader());
    //...

```

You can see that the ```buildHeader``` function does not return the ```options``` parameter in the constructor.

**Comment by blake-simpson** [comment]
Hi @1280103995,

Thanks for the issue. Can you please describe/show your use case and what problem you are experiencing?

**Comment by 1280103995** [comment]
> Hi @1280103995,
> 
> Thanks for the issue. Can you please describe/show your use case and what problem you are experiencing?

Here is the example I used:
```
import JWT from 'expo-jwt';

const secret = "0gmxJA";
const key_id = "app_664";
const payload = {
     scope: 'user',
     external_id:'123456',
};
const header = {
     kid: key_id,
};
const JWTtoken = JWT.encode(payload, secret, header);
```

Then modify the source code and add the following log below
```
const jsonHeader = JSON.stringify(this.buildHeader()); 
console.log('JWT Header',jsonHeader);  //add the line
```
You will get ```{"alg":"HS256","typ":"JWT"}```，while I want to get ```{"alg":"HS256","typ":"JWT", "kid": "app_664"}```
--------------------------------------------------------------------------------------------------------------------------
Therefore
```
buildHeader(): JWTHeader {
   return { 
         alg: this.options.algorithm, 
         typ: 'JWT', 
  }; 
}
```
 should be changed to 
```
buildHeader(): JWTHeader { 
    return { 
          alg: this.options.algorithm, 
          typ: 'JWT' , 
          ...this.options, //add the line 
   }; 
}
```

**Comment by blake-simpson** [comment]
Ok that makes more sense, my question is more though why do you need to do that? Although it is a public method I assumed `buildHeader` was more of a private method used internally by `encodeAndSign`. Do you not already have this information when encoding?

I think there is a valid point here though. This library respects all body claims but not the optional header ones (only `alg`). I think it would make the most sense to expand the `EncodingOptions` to allow `kid` and all of the other optional claims from the spec (https://www.rfc-editor.org/rfc/rfc7515#section-4.1) instead of just spreading the options back through the header. 

I can make a PR for this but it's a larger piece of work and I can't do it immediately. I am happy if you propose a PR and we can go through it together? Otherwise I will try to build this out soon, as it makes sense for the library to have in general.

**Comment by 1280103995** [comment]
> why do you need to do that?

My App integrates the Smooch SDK, and the login method requires JWT, which requires such a header. 
I made a patch to solve my problem.

Also, I'm not good at PR. :sweat:

**Comment by blake-simpson** [comment]
Ok no problem, if you can use your patch for now I will try to carve some time to implement the JWT headers properly and get back to you for feedback.

**Comment by blake-simpson** [comment]
Hi @1280103995,

I've made some changes and created a PR here: https://github.com/blake-simpson/expo-jwt/pull/42
Would you be able to take a look and see if that would satisfy your needs?

FYI I wondered how I had missed these claims when building the library. I discovered that the [7519 standard](https://datatracker.ietf.org/doc/html/rfc7519#section-5) which I originally built against doesn't include these extra header claims. The older [7515 standard](https://www.rfc-editor.org/rfc/rfc7515#section-4.1.4) did however so I have added these in the interests of backwards compatibility, since it doesn't prevent `expo-jwt` from working as it currently does.

Please let me know your thoughts then I could prep a release next week :)

**Comment by 1280103995** [comment]
> Hi @1280103995,
> 
> I've made some changes and created a PR here: #42 Would you be able to take a look and see if that would satisfy your needs?
> 
> FYI I wondered how I had missed these claims when building the library. I discovered that the [7519 standard](https://datatracker.ietf.org/doc/html/rfc7519#section-5) which I originally built against doesn't include these extra header claims. The older [7515 standard](https://www.rfc-editor.org/rfc/rfc7515#section-4.1.4) did however so I have added these in the interests of backwards compatibility, since it doesn't prevent `expo-jwt` from working as it currently does.
> 
> Please let me know your thoughts then I could prep a release next week :)

Sorry for the late reply. I tested this PR and it works fine.

**Comment by blake-simpson** [comment]
Ok thank you, I will merge this PR and release it as 1.8.0.

Thanks again for the issue :)

**Comment by blake-simpson** [comment]
That's 1.8.0 available on NPM now. If there's any issues just let me know!
