### ISSUE TITLE
Skip Signature Verification

### ISSUE THREAD

**Issue by CarlosMayoralMX** [blake-simpson/expo-jwt#9]
Hello,

I was wondering if it would be possible to add the possibility of skip signature verification. Because as long as i understand the client (in this case the expo mobile application) is not supposed to know the secret

Regards..

**Comment by blake-simpson** [comment]
Hey,

I understand it can be a risk to put a secret into your app. There are strategies like splitting up the key into separate strings and importing them from separate files, or rotating to new secret keys on each app release, but you can never guarantee safety.

If you do not want to have a secret in your app and do not want to verify the tokens, I would suggest instead of using a library you can simply take the body (middle) section of the JWT token and decode that directly.

Something along the lines of:

```js
const token = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIifQ.Kyojwz8Z5SckLbMU-EImuzHEjjg_1apSOLz_tsZQj1025OH--qaORzkHUkScScd8-RZnWUdCu0epiaofQZNkBA';
const body = token.split('.')[1];
const decoded = atob(body);
JSON.parse(decoded);
// => {foo: "bar"}
```

I think React Native does not have a `atob` function natively, but you can add a small helper for one, like so: https://snack.expo.io/BktW0xdje

Cheers,
Blake

**Comment by CarlosMayoralMX** [comment]
Hi,

Understood! Thanks for the response.

Saludos,
Carlos
